### ISSUE TITLE
what will we support?

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/data-repository-service-schemas#139]

**Comment by denis-yuen** [comment]
Indeed

**Comment by david4096** [comment]
@denis-yuen this is an epic from JIRA that synced quite beatifully as you can see. Feel free to add your thoughts on what will be necessary to support. Here's a list of issues, the first category are code related improvements or additions that are fairly low complexity. The second are issues that may require some more discussion or evaluation and documentation. They're at least partly in order of importance.

Looking at this list, the main schema changes are: add auth info to URLs, identifier resolution metadata to GetDataObject response, and an email to service-info. The remaining issues provide better documentation, improve the usefulness of the client software and help in designing software that will use DOS.

#133 Test improvements
#70 Document Python client usage
#125 Schema validation warnings
#137 Packaging bug
#44 Implement CLI client
#114 Load OpenAPI description locally
#119 Data Bundle Checksum Tests
#136 Add contact info to service info
#90 Swagger UI Points at inactive service

#65 Identifier Resolution Provenance *
#17 Document expected behavior
#121 Document Compliance Levels
#49 DOS Protocol scheme
#89 Enumerating checksum types
#47 Authorization metadata per URL *
#9 Document versioning
#77 Bundle Use Case documentation
#74 How to Resolve Services
#15 Metadata formatting documentation
