### ISSUE TITLE
Update schema based on Aaron and Phillis' auth doc

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/data-repository-service-schemas#229]
https://docs.google.com/document/d/1hj7hY2pqlMvHEI-6pM-prj0LPUo9MRxzGOTnwq85tpo/edit

**Comment by rishidev** [comment]
Public versions of the authentication and authorization work in DRS 1.0 and how it relates to WES in the <1 year timescale. [Document available here](https://docs.google.com/document/d/1hj7hY2pqlMvHEI-6pM-prj0LPUo9MRxzGOTnwq85tpo/edit).

**Comment by briandoconnor** [comment]
Let's see if we can get Aaron and/or Phillis to make schema/docs changes.

**Comment by dglazer** [comment]
See also prior discussion in #47 (especially the comment by @mfiume at https://github.com/ga4gh/data-repository-service-schemas/issues/47#issuecomment-402524882).

**Comment by dglazer** [comment]
There was a side thread with Aaron discussing alignment between his doc and #236 -- conclusion was "_not bad, with some loose ends that can be addressed later_" -- see below for a summary.

**From: David Glazer**
#236 tries to strike a reasonable balance between hard-coded support for individual access methods and a fully generic approach. The main difference in intent I see between its approach and the scenarios in the doc is how generic they are -- your second is specific to signed URLs; your third returns an auth header that can be used with any URL (but requires you to know the URL). In that light, I see #236 as being somewhere between -- it uses generic language that isn't specific to signed URLs, and it works with any URL, but the lack of an auth header is limiting.

Given that, I'm curious how you'd feel if we added an optional auth header to the response to the `/objects/<object_id>/access/<access_id>` method in #236, as is now proposed in #239. Then you could still use it for signed URLs, but you could also use it for any other access method where the DRS server was capable of generating everything the client needed to fetch bytes.

**From: Aaron Kemp**
The pull request as it stands (unless I misunderstood) doesn't actually enable support for things like FTP since it doesn't specify a particular schema that would be returned for that access method (eg, username/password). Is the thinking that we would have 'ftp' or 'gsiftp' specify the other required information (eg, username password) in the returned URL? (for example `ftp://user:pass@host.com/abc/def.bam`?)

**From: David Glazer**
My summary of your remaining concerns:

1) the big one is the appropriate scope for DRS
    * the general ideas in #236 (get list of options to fetch an object --> get details on how to use one of those options, including auth --> get bytes) all make sense to you
    * you'd prefer to have them split up differently into separate services (e.g. what's in search vs. DAM vs. DRS)
    * having said that, you don't have any showstopper concerns

2) there are some rough edges in the details
    * e.g. how would we provide the username and password for an ftp method?
    * e.g. we haven't actually specified any way to get auth headers for any method
 
If that's right, I feel good about where things stand -- we can continue to fix up the rough edges (e.g. your suggestion for ftp) (e.g. see #239), get things working while factored this way, and then once more services are live refactor if it makes sense.

**From: Aaron Kemp**
Looks right to me :)

**Comment by dglazer** [comment]
We should be able to close this after PR #248 (which resolves issue #239) is merged.

**Comment by briandoconnor** [comment]
@dglazer sounds good!

**Comment by dglazer** [comment]
PR #248 is now merged.
