### ISSUE TITLE
Should we allow slashes in DRS IDs?

### ISSUE THREAD

**Issue by susheel** [ga4gh/data-repository-service-schemas#263]
Following our last meeting, there was a discussion if we should explicitly disallow forward-slashes `/` in a DRS `id`. Zac (NIH Data Commons) uses dataguids and/or ark ids as DRS ids which have forward-slashes in them.

The current documentation does allow forward-slash. See [front-matter.adocL#13](https://github.com/ga4gh/data-repository-service-schemas/blob/master/docs/asciidoc/front_matter.adoc#L13)
> DRS IDs are URL-safe text strings made up of alphanumeric characters and any of [.-_/]

Error Conditions:

1. GET `drs://<server>/<foo/access>` (where `<foo/access>` is the DRS id)
2. GET `drs://<server>/<foo/access/1234>` (where `<foo/access>` is the DRS id)

The above requests will not return the expected `Object` definition, but an `Error` definition as the DRS server expects an `access_id` after `/access` as per the [current spec](https://github.com/ga4gh/data-repository-service-schemas/blob/cd0186fa9b7763bdb15175e6615ff4a42c1b85c3/openapi/data_repository_service.swagger.yaml#L117)

Possible Solutions:

- Disallow `forward-slashes` in a DRS `id`; OR
- Restructure the AccessMethod API:
  From: `GET /objects/{object_id}/access/{access_id}`
  To: `GET /access/{access_id}`

**Comment by sarpera** [comment]
I'm voting for disallowing forward-slashes in a DRS id. 

Restructuring AccessMethod URLs in the way proposed here would mean `access_id`s would have to be unique to a DRS server. Currently they are unique to an `object`.

Also, we might have more endpoints than `/access` in the future that would be appended to `/objects/{object_id}/`. IDs with slashes would complicate parsing this. 

IMHO GUIDs should not be used as a replacement for an `object_id`. Most GUIDs already have a prefix and an identifier, similar to an object in DRS (drs://<server>/<id>). In practical terms, a client would need both DRS server part and the full GUIDs to get a "DRS response" for a given object/bundle. 

No doubt the GUIDs are quite useful and I'm all up for using any sort of GUIDs as an alias but not the primary identifier for an object. We could provide a GET method using an alias like:
GET `/objects/?alias=<GUID>` 
which could translate into:
`drs://<server>/?alias=<GUID>`

**Comment by jaeddy** [comment]
-1 (agree with @sarpera)

**Comment by tetron** [comment]
@susheel I would say that identifiers can be URI-quoted, and slashes must be quoted, so you would use URI quoting `%2F` for a slash in the identifier.

**Comment by susheel** [comment]
@tetron Just presenting the case on behalf of the discussion that was held at Hinxton.

I'm not an avid supporter of using slashes in DRS IDs. Just pointing out that the current DRS spec supports slashes... - [front-matter.adocL#13](https://github.com/ga4gh/data-repository-service-schemas/blob/master/docs/asciidoc/front_matter.adoc#L13)

> DRS IDs are URL-safe text strings made up of alphanumeric characters and any of [.-_/]

...and if DPs or implementors use the spec as-is will lead to error conditions.

The decision for the group is whether to:
1. Explicitly disallow slashes in the spec
2. Rewrite the spec to support slashes

Both have their pro/cons. This issue to flesh this out. I think we need to also hear out the other side :P

E.g. A simple example would be to provide slashed access to named objects within a bundle - `drs://<server>/<bundle-id>/foo.bam` If this file does not exist in the bundle 404 is returned.

**Comment by susheel** [comment]
Personally, I wouldn't use slashes. I would use CURIE syntax with `:`

**Comment by briandoconnor** [comment]
We decided today to make a PR where we document using URL encoding if someone wants to include a "/" in the ID

**Comment by susheel** [comment]
2019-05-20 GA4GH Cloud call summary:

- Slashes will be permitted only if they are URL-encoded
- PR will be submitted to update the documentation

**Comment by reece** [comment]
We're having a very similar discussion over in the VR group in ga4gh/vr-spec#32. I'm hoping that we can put our heads together to reason through this thorny issue.

The essential issue is this: We'd like to use CURIEs to structure ids and a CURIE may, in principle, contain a / in the `reference` portion of the CURIE. There are significant pros and cons to using / in CURIEs. So, should we?

Let's consider some use cases for ids. We're considering two broad id options:  a path form like `ga4gh:VA/abcd_0123` and a non-path "flattened" form like `ga4gh:VA_abcd_0123` (notice delimiter before the digest). The digest is base64url encoded, so guaranteed to be safe in a URL segment.

* Generation:
  * Both are equally easy to generate.

* Use as an identifier (e.g., in a database):
  * If treated as an opaque identifier, they work equally well.
  * If clients try to parse (e.g., to infer the type), the path form is preferable because the parse rules are those of URIs themselves and not a custom rule like "first 2 chars are type" or "up to first underscore, but careful because underscores are part of the digest".

* CURIE expansion. The CURIE spec anticipates expanding the prefix with a base URI in order to retrieve a resource. 
  * With the path form, the expansion points directly to the resource as is. No client side work is needed other than expansion.
  * With the non-path form, all objects would be flattened to the api root. This, in turn, would require that the server would have to either rewrite the URL or disambiguate the id and redirect (301?) to the appropriate endpoint. For example, http://somewhere/v1/VA_abcd_01234 → http://somewhere/v1/allele/VA_abcd_01234. (I suspect that clients would learn to preemptively rewrite queries, which would make them tightly coupled with the identifier format. :-()

* Use *within* URIs.
  * With the path form, every id will need escaping because we know that it contains a /.
  * With the non-path form, people will just string concatenate and get away with a bad habit of not escaping ids.

As a standards group, my opinion is that we should be using standards and expecting that others do so. People should be escaping *all* identifiers in case they contain reserved characters, whether called a CURIE or otherwise, because that's how you comply with RFC3986. So, our debate really comes down to whether we tailor our spec to accommodate the practice of people not needing to understand escaping, and do so at the cost of some benefits of URI path structure.

A related issue is a matter of design principle: I'm troubled by the specter of using CURIE as a named type, but to attach caveats so that clients don't have to use it properly.  If we say we're generating CURIEs, then clients should treat it as a CURIE and *always* escape that content for use in a URI. Conversely, if we want a type that people don't have to escape, then we should not call it a CURIE and attach caveats for how to use them incorrectly.

**Comment by ahwagner** [comment]
I'd like to second @reece in requesting that participants of this discussion leave their comments over at ga4gh/vr-spec/issues/32. It would be very helpful for that decision if Cloud WS members also commented.

@susheel @sarpera @jaeddy @tetron @briandoconnor

**Comment by susheel** [comment]
@ahwagner @reece I think the consensus at yesterday's GA4GH call was to disallow slashes in the IDs. You may still custom-encode slashes using the unserved chars [A-Za-z0-9.-_~] but may not be supported by other DRS implementations.

**Comment by dglazer** [comment]
resolved by #271
