### ISSUE TITLE
Persistent Identifiers and Prefixes

### ISSUE THREAD

**Issue by MichaelLukowski** [ga4gh/data-repository-service-schemas#306]
Right now the DRS endpoints only support simple object matching like

`drs://example.com/{object_id}`

As a driver project we have identified potential problems with endpoints using only using the server name and object id. We have found that working with funding from others and working with multiple large groups that URLs change for a variety of reasons. 

As it stands now a simple URL change from `example.com` to `foobar.com` would result in all of the previous DRS endpoints being broken. This is a problem as DRS cannot be used as a persistent identifier, thus researchers using these data sets cannot reliably cite these objects in their publications and research.

The solution we would like to propose would be a simple prefix in the URL to allow for an existing resolution service, like numbers to things (n2t.net) or identifiers.org, to resolve the endpoint in the event that a request returns a 404. The new endpoint would look something like 

`drs://example.com/{prefix}/{object_id}`

This change would allow DRS to align with ARKs (https://en.wikipedia.org/wiki/Archival_Resource_Key) and DOIs (https://en.wikipedia.org/wiki/Digital_object_identifier)

**Comment by dglazer** [comment]
Michael, thank you for starting an issue to track this discussion. I'm adding a link to the [discussion document](https://docs.google.com/document/d/1E2dRQeGEtE1koBsYQTj6hadmENQABJHoLXGY9vFGwZ8/edit#heading=h.v4n2syv7eyfc) we've been using, in case others find that background, and the open questions it raises, useful context.

Two comments on the issue itself:
- this may be pedantic, but I disagree that "_DRS endpoints only support simple object matching_" -- I'd say they do even less than that, and instead are simple REST methods that only do exactly what they're asked to do. The `drs://` syntax you list isn't part of any DRS endpoint; it's a recommended text interchange format that's parsed by DRS clients, and tells them what DRS server to connect to, and what request to send to what endpoint. (In exactly the same way that `http://` syntax is parsed by HTTP clients and tells them what server to connect to, and what request to send to what endpoint.)
- as discussed in the document, directionally I'm all for the idea of adding a prefix of some sort that clients can use to find the right DRS server, and then ask it how to fetch content described by a server-relative id. The trick is in the details of how the prefix is assigned, specified, and resolved. I look forward to seeing a specific proposal.

**Comment by pgrosu** [comment]
The link to the discussion document does not seem to be open to the public -- my email is pgrosu@gmail.com so I could be added please.  So the solution is usually done via another approach (somewhat discussed in the weblinks), but also allows for scalability in data access.  An older approach that can work here is done by decoupling the `id` from the `location`, where location becomes a `Set`/`List` operated on through routing or lookup service.  Thus the abstraction to fix it is to have object `id`s (or bundles) mapped to a `Set`/`List` of locations, which can contain lookup service links themselves.  You can think of them as follows via reverse-lookup to a dynamically changing table, that such service endpoints would provide for discovery:

| object id  | location list |
| ------------- | ------------- |
| id_1  | [drs/http]://example.com/id_1, [drs/http]://foobar.com/id_1, http://routing.service.lookup.com/id_1  |

Such service endpoints would need to be kept by a collection of authorities in order to ensure consistency.  Then in the publication you also add the list of authorities in order to provide the guarantee of data reachability.

Hope it helps,
~p

**Comment by ianfore** [comment]
Suggesting this issue might be ready to be closed. Everything seems to be picked up in #318 .

**Comment by briandoconnor** [comment]
Closing since #318 has been merged
