### ISSUE TITLE
Authorization metadata per URL

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-repository-service-schemas#47]
Some DOS installations present private and controlled access data. To make it easier for clients to find out the proper authentication credentials to use, add a `ServiceInfo` that offers a URL for logging in.

**Comment by zflamig** [comment]
Need to consider that the DOS installation which knows about the data may not be the same one which can access the data doing it in one shot with sending the DOS server your auth info may not be the best way.

How will we know which protocols the auth URL speaks? There may need to be a standard around that too or a list of options... consider FTP with anonymous access or quasi anonymous (email registered with any password) or HTTP with basic auth only?

**Comment by david4096** [comment]
In order to avoid enumerating all the possible schemes different URLs might enforce, my hope was to offer this as a simple matter of service with some helpful URLs. You're right that the same service might host several URLs that all offer different authentication mechanisms.

To that end, it seems like a list of pairs of protocols and URLs might offer a minimum workable solution.

For example, imagine that we host the Thousand Genomes data via DOS. We list both S3 URLs and ftp locations for each item. We want to convey to the client enough information so that can properly form a request that includes their credentials, or a way to begin to gather credentials.

To currently satisfy this use case, note that the `url` field of a Data Object can include metadata. Without other guidance, one could define keys in the `user_metadata` that could instruct a client to set anonymous FTP details, or that the S3 data was publicly downloadable without requester pays.

Since we expect these metadata to be shared across many items in this repository, we could add these tuples to the `ServiceInfo` endpoint to make its use more clear and to help constrain the useful keys. If there are multiple authentication schemes for one protocol type (http basic auth, oauth...) for Objects behind a service, this could get complicated.

We may find in practice that a limited useful set of terms will be used, for example, doing this for [fence](https://github.com/uc-cdis/fence) one might want to include the "authorize" and "token" endpoints. This would make it easier for a "fence aware downloader" to work with a DOS.

Perhaps instead of trying to add an endpoint, we could constrain the keys used for describing the URL metadata. So, add a new key to the URL field of a data object (which is already an object that can include `system_metadata` and `user_metadata`) that is something like `authorization_metadata` and be instructive about useful keys? https://github.com/ga4gh/data-object-service-schemas/issues/25

**Comment by david4096** [comment]
A target for interoperation for this service's response would be in assisting clients in generating a `keychain.json` of the bdbags downloader. https://github.com/fair-research/bdbag/blob/master/doc/config.md#keychain.json

**Comment by dvoet** [comment]
Is there are concrete use case for general discoverability of how to auth? I know my use case where I already know about fence and what to do. So all I need to know is that it is fence and I can do the rest. When we figure out the next thing after fence it will probably be different enough.

My suggestion is that to start we do something simple and maybe not so well defined like the url metadata and don't spend too much time thinking further out.

**Comment by david4096** [comment]
This came up on a call today. If you want to experiment with this, try putting the fence URLs in the `system_metadata` of the `URL` object.

**Comment by mfiume** [comment]
@dvoet and @david4096, thank you so much for leading this discussion. We have concrete use cases emerging out of Discovery Work Stream. Imagine this scenario: a user uses a Discovery API to search across a network of services (concretely, Beacon Network searching across Beacons, which have added support for payloads which might include DOS objects. We want to pass these off to a WES implementation, but because the DOS objects have been found across a wide network, it can't possibly know a priori what provider (i.e. cloud) or auth protocol the data are served by.

I agree very much with @david4096's post on May 4th.

I'll play back our line of thinking here for additional feedback:

**Background**
DOS and WES are emerging standards for files and workflow executor services that are necessary for making data and workflows portable across different compute environments.

**Problem**
It is unclear how a WES implementation can marshal secured access files referred to by a DOS object, without additional information about authorization. 

**Opportunity**
If solved, we will be able to reliably and securely utilize large volumes of secured access data as inputs to workflows.

**Assumptions**
- WES endpoint has no prior knowledge about the DOS file provider, i.e. where the files are stored and authorized. Why? Imagine a use case where DOS objects are obtained through various sources (e.g. a future implementation of Beacon Network).

**Observations**
- The provider cannot always be inferred from the URL. For example, files on GCP have URLs like gs://*, but on Azure and local storage URLs are like http://*.
- Signed URLs are not suitable. They expire (problem for reproducibility) and can easily be compromised (problem for security).

**Implications**
- WES endpoints should be told about provider and authorization information explicitly, for each input, either within the DOS payload or in parallel. 

**Proposals**

Option 1: embed authorization information optionally in DOS

_DOS Object_
`{
  "data_objects": [
    {
      "id": "string",
      "name": "string",
      "size": "string",
      "created": "2018-07-04T03:46:22.754Z",
      "updated": "2018-07-04T03:46:22.754Z",
      "version": "string",
      "mime_type": "string",
      "checksums": [
        {
          "checksum": "string",
          "type": "string"
        }
      ],
      "urls": [
        {
          "url": "string",
          "provider_metadata": {
            "provider": "google"
            "auth_type": "OAuth 2.0"
            "auth_url": "https://accounts.google.com/o/oauth2/token"
          },
          "system_metadata": {
            "additionalProp1": {}
          },
          "user_metadata": {
            "additionalProp1": {}
          }
        }
      ],
      "description": "string",
      "aliases": [
        "string"
      ]
    }
  ],
  "next_page_token": "string"
`

Option 2: Don't include authorization information in DOS, but rather alongside the WES request

_WES Request_
`...
"workflow_params": {
   "inputs": [
       {
        dos: <dos_object>,
        "provider_metadata": {
          "provider": "google"
          "auth_type": "OAuth 2.0"
          "auth_url": "https://accounts.google.com/o/oauth2/token"
        }
     }
   }
}
...
`

PS: We much prefer option 1!

**Comment by david4096** [comment]
Thanks for taking the time to write this out @mfiume . For what it's worth, if you have bandwidth to put together a schema PR we'd love to test it out. Option 1 seems more clear than overloading `system_metadata` by adding a named key. I think having an implementation that can practically get tokens from UC-CDIS fence and google will keep us unblocked for the medium term.

The way this works for us in practice is that we only ever pass around DOS identifiers. The workflow executor or provisioner (localizer?) handles the DOS request and any auth concerns. With these additions we should have sufficient information for getting a token or signed URL for accessing WES inputs.

**Comment by david4096** [comment]
Following the above conversation, I suggest this PR should close with an `authorization_metadata` field being added to the Data Object `url` message following Marc's comment. A test demonstrating its value should be devised.

Note that both the oauth url and a refresh token URL might be useful to provide.

Then, when one goes to perform a workflow execution, they can provide authorization information as needed to sign a cloud native URL when doing provisioning. This makes it more clear how concerns are separated so that executors can make a request against DOS to further sign a URL as necessary.

**Comment by dvoet** [comment]
Why was this closed? Is there a resolution?

**Comment by sarpera** [comment]
Seems like #213 needs to incorporate the use cases here, specifically the access methods that won't be accessed via `/objects/<id>/<access_id>` path e.g ftp, http etc

@susheel @dglazer what's your take on this?

**Comment by dglazer** [comment]
@dvoet -- it was closed as part of a batch cleanup of old mostly-stale issues -- hearing no objections for 10 days, we went ahead and closed them.

@sarpera -- I think we can ignore auth from the first PR for #213, and then add in what's needed as part of #229. I'll add a note there referencing the good discussion here.
